version: "2.1"

services:

  mongodb:
    image: mongo:6
    command: mongod --replSet dbrs --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - mongo-network
    healthcheck:
      test: test $$(mongosh --eval 'db.adminCommand("ping")' | grep -c "ok") -eq 1
      interval: 2s
      timeout: 3s
      retries: 5

  mongo-init:
    image: mongo:6
    restart: "no"
    networks:
      - mongo-network
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./docker/mongodb/init-rs.sh:/scripts/init-rs.sh
      - ./docker/mongodb/init-user.js:/scripts/init-user.js
    command: /bin/bash /scripts/init-rs.sh

networks:
  mongo-network:
    driver: bridge